try:
    print('try')
    raise Exception('エラーです。')
except:
    print('except')
    raise
